### ISSUE TITLE
Boot Fails after restart

### ISSUE THREAD

**Issue by deepshankaryadav** [dtag-dev-sec/t-pot-autoinstall#13]
Hi,

I have recently installed T-PoT on one of the PC I have.

Now I am facing an issue after install when system restarts I just get a blank screen. 

Have tried installing via Image and Autoinstaller both.

**Comment by mattmac1** [comment]
I would say the underlying OS is the problem... Do a clean install on the
listed supported Linux versions

On 10 Apr 2017 12:09, "Deep Shankar Yadav" <notifications@github.com> wrote:

Hi,

I have recently installed T-PoT on one of the PC I have.

Now I am facing an issue after install when system restarts I just get a
blank screen.

Have tried installing via Image and Autoinstaller both.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtag-dev-sec/t-pot-autoinstall/issues/13>, or mute the
thread

**Comment by vorband** [comment]
cannot reproduce. Installer works fine on Ubuntu 16.04. 
Maybe your hardware is not properly supported running Ubuntu 16.04.

**Comment by deepshankaryadav** [comment]
Solved it! It was a hardware issue. 

Worked Fine after disabling secure boot and starting legacy support in bios.

@vorband  I have emailed you regarding T Pot Sensor Network. Please reply. Thanks.
