### ISSUE TITLE
Fully automated install?

### ISSUE THREAD

**Issue by ctindel** [dtag-dev-sec/t-pot-autoinstall#29]
Any chance you could enhance the install script to have command line options for everything so that it can be fully automated instead of prompting?  I used to use an expect script to do it from the ISO repo but it seems that install script has changed and the changes to deal with the www.nsanamegenerator.com going away have broken it.  For example I used to do this:

```
#!/usr/bin/expect -d

## Expect Parameters
set timeout 10000
set successMsg "Status: Success"
set failureMsg "Status: Failure"
log_user 1


#spawn /root/tpot/iso/installer/install.sh
#expect "Install Type:" {send "E\r"}
#expect "Username (tsec not allowed):" {send "username\r"}
#expect "OK (y/n)?" {send "y\r"}
#expect "Password:" {send "password\r"}
#expect "Repeat password:" {send "password\r"}
#expect "Country Name (2 letter code) \\\[AU\\\]:" {send "\r"}
#expect "State or Province Name (full name) \\\[Some-State\\\]:" {send "\r"}
#expect "Locality Name (eg, city) \\\[\\\]:" {send "\r"}
#expect "Organization Name (eg, company) \\\[Internet Widgits Pty Ltd\\\]:" {send "\r"}
#expect "Organizational Unit Name (eg, section) \\\[\\\]:" {send "\r"}
#expect "Common Name (e.g. server FQDN or YOUR name) \\\[\\\]:" {send "\r"}
#expect "Email Address \\\[\\\]:" {send "\r"}
#expect eof
```

I tried to do something similar with this autoinstall repo but since I run this from cloud-init and there's no PTY available I think maybe some of the apt-get commands are dying or something, I'm not sure.

Anyway if you could change this so it took no input other than the CLI and just ran, it would be awesome!

**Comment by vorband** [comment]
Automated install is now supported in latest version. Please have a look at the readme.md. 

-- >8 --
Due to public demand, we added a non-interactive installation option. Just add the username, the number referencing the edition and the password for web access to the installation script, e.g.

./install.sh ubuntu 2 myPassw0rd
will install the Honeypot Only Edition (2) for the user "ubuntu" and set the web access password to "myPassw0rd".
-- 8< --
